[tool.poetry]
name = "jalali_pandas"
version = "0.2.0"
description = "A Pandas extension to make work with Jalali Date easier."
authors = ["Mehdi Ghodsizadeh <mehdi.ghodsizadeh@gmail.com>"]
license = "GPL-3.0-only"
readme = "README.md"
homepage = "https://ghodsizadeh.github.io/jalali-pandas/"
repository = "https://github.com/ghodsizadeh/jalali-pandas"

[tool.poetry.dependencies]
python = "^3.6"
jdatetime = "^3.6.4"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/ghodsizadeh/jalali-pandas/issues"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
